<?php

namespace natof;

use natof\command\SetGrade;
use natof\event\PlayerListener;
use natof\manager\ConfigManager;
use pocketmine\permission\Permission;
use pocketmine\permission\PermissionManager;
use pocketmine\plugin\PluginBase;
use pocketmine\Server;

class GradeEasy extends PluginBase{

    private static GradeEasy $instance;

    /**
     * @return static
     */
    public static function getInstance(): self
    {
        return self::$instance;
    }

    protected function onEnable(): void
    {
        @mkdir(self::getInstance()->getDataFolder() . "save");
        $this->saveResource("grade.yml");
        $this->getServer()->getPluginManager()->registerEvents(new PlayerListener(), $this);
        Server::getInstance()->getCommandMap()->register("grade", new SetGrade());
            PermissionManager::getInstance()->addPermission(new Permission("grade.use"));
        parent::onEnable();
    }

    protected function onLoad(): void
    {
        self::$instance = $this;
        parent::onLoad(); // TODO: Change the autogenerated stub
    }
}